version: "3.8"
services:
  postgres:
    image: postgres:latest
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env.production

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gift
    env_file:
      - .env.production
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
